using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Xml.Linq;
using System.Text.RegularExpressions;

namespace BpToolsWPFClientTest
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        BpToolsLib.StageSet stageSet;

        public MainWindow()
        {
            InitializeComponent();
        }

        private void RefreshXml()
        {
            XmlData.Text = new BpToolsLib.Generator.Generator(stageSet).GetXml();
        }

        private void CopyXml()
        {
            Clipboard.SetText(new BpToolsLib.Generator.Generator(stageSet).GetXml());
        }

        private void AddRenameMenu()
        {
            foreach (UIElement elem in Canvas1.Children)
            {
                if (elem is Stage)
                {
                    Stage stage = (Stage)elem;
                    stage.ContextMenu = new ContextMenu();
                    MenuItem menuItem = new MenuItem() { Header = "Refactor rename" };
                    menuItem.Click += (sender, e) =>
                    {                       
                        DataRenameWindow dialog = new DataRenameWindow()
                        {
                            DataName = stage.BpStage.Name
                        };

                        if (dialog.ShowDialog() != true)
                        {
                            return;
                        }

                        BpToolsLib.Tools.RefactorRename.Rename(stage.BpStage, stageSet, dialog.DataName);
                        StageSetRedraw.Draw(Canvas1, stageSet);
                        AddRenameMenu();
                        RefreshXml();
                    };
                    stage.ContextMenu.Items.Add(menuItem);
                }
            }
        }

        private void PasteXml()
        {
            stageSet = null;
            BpToolsLib.IBaseElement element;
            try
            {
                element = new BpToolsLib.Interpreter.Interpreter(Clipboard.GetText()).GetElement();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Exception: " + ex.Message);
                return;
            }
            if (!(element is BpToolsLib.StageSet))
            {
                return;
            }

            stageSet = (BpToolsLib.StageSet)element;
            StageSetRedraw.Draw(Canvas1, stageSet);
            AddRenameMenu();
            RefreshXml();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            PasteXml();
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            CopyXml();
        }

        private void Window_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.V && Keyboard.Modifiers == ModifierKeys.Control)
            {
                PasteXml();
            }
            if (e.Key == Key.C && Keyboard.Modifiers == ModifierKeys.Control)
            {
                CopyXml();
            }
        }

        private void MenuItem_Click(object sender, RoutedEventArgs e)
        {
            CollectionGeneratorDialog dialog = new CollectionGeneratorDialog();
            if (dialog.ShowDialog() != true)
            {
                return;
            }

            try
            {
                stageSet = new BpToolsLib.StageSet()
                {
    BpToolsLib.Tools.CollectionBuilder.BuildCollectionFromTabData(
        "Collection",
        "Autogenerated collection",
        dialog.TabData
        )
                };
            } 
            catch (Exception ex)
            {
                MessageBox.Show("Exception: " + ex.Message);
                return;
            }

            StageSetRedraw.Draw(Canvas1, stageSet);
            AddRenameMenu();
            RefreshXml();
        }

        private void MenuItem_Click_1(object sender, RoutedEventArgs e)
        {
            BpToolsLib.Tools.DeleteUnused.DeleteUnusedDataAndCollection(stageSet);
            StageSetRedraw.Draw(Canvas1, stageSet);
            AddRenameMenu();
            RefreshXml();
        }
    }
}
